let movies = [
    { title: "The Godfather" },
    { title: "Interstellar" },
    { title: "The Matrix" },
    { title: "The Lord of the Rings: The Fellowship of the Ring" },
    { title: "Citizen Kane" },
    { title: "Inception" },
    { title: "Pulp Fiction" },
    { title: "Seven Samurai" },
    { title: "City of God" },
    { title: "The Great Dictator" },
    { title: "The Silence of the Lambs" },
    { title: "Forrest Gump" },
    { title: "Fight Club" },
    { title: "Spirited Away" },
    { title: "Pan's Labyrinth" },
    { title: "Terminator 2: Judgment Day" },
    { title: "Saving Private Ryan" },
    { title: "Psycho" },
    { title: "Back to the Future" },
    { title: "Scarface" },
    { title: "The Lord of the Rings: The Return of the King" },
    { title: "Star Wars" },
    { title: "The Shining" },
    { title: "The Pianist" },
    { title: "Schindler's List" },
    { title: "The Lord of the Rings: The Two Towers" },
    { title: "Gladiator" },
    { title: "The Lion King" },
    { title: "Titanic" },
    { title: "Amélie" },
    { title: "Django Unchained" },
    { title: "2001: A Space Odyssey" },
    { title: "The Truman Show" },
    { title: "The Wolf of Wall Street" },
    { title: "The Dark Knight" },
    { title: "The Sixth Sense" },
    { title: "Life Is Beautiful" },
    { title: "Amélie" },
    { title: "The Breakfast Club" },
    { title: "Whiplash" },
    { title: "Matrix Reloaded" },
    { title: "Kill Bill: Volume 1" },
    { title: "Kill Bill: Volume 2" },
    { title: "Monty Python's Life of Brian" },
    { title: "The Terminal" },
    { title: "The Big Lebowski" },
    { title: "Scarface" },
    { title: "Singin' in the Rain" },
    { title: "All About Eve" },
    { title: "Blade Runner" },
    { title: "Batman Begins" },
    { title: "Iron Man" },
    { title: "The Incredibles" },
    { title: "E.T. the Extra-Terrestrial" },
    { title: "Pirates of the Caribbean: The Curse of the Black Pearl" },
    { title: "Beauty and the Beast" },
    { title: "The Shape of Water" },
    { title: "The Revenant" },
    { title: "Raiders of the Lost Ark" },
    { title: "The Pianist" },
    { title: "Eternal Sunshine of the Spotless Mind" },
    { title: "The Usual Suspects" },
    { title: "Fight Club" },
    { title: "Inception" },
    { title: "American Beauty" },
    { title: "The Sixth Sense" },
    { title: "The Shining" },
    { title: "Memento" },
    { title: "Donnie Darko" },
    { title: "Edward Scissorhands" },
    { title: "Black Swan" },
    { title: "Dead Poets Society" },
    { title: "Catch Me If You Can" },
    { title: "The Elephant Man" },
    { title: "Rise of the Guardians" },
    { title: "Life of Pi" },
    { title: "The Skin I Live In" },
    { title: "Inception" },
    { title: "Oldboy" },
    { title: "The Fountain" },
    { title: "Saving Private Ryan" },
    { title: "Schindler's List" },
    { title: "The Shawshank Redemption" },
    { title: "Goodfellas" },
    { title: "The Green Mile" },
    { title: "The Departed" },
    { title: "The Godfather Part II" },
    { title: "The Prestige" },
    { title: "The Dark Knight Rises" },
    { title: "Inglourious Basterds" },
    { title: "Django Unchained" },
    { title: "Reservoir Dogs" },
    { title: "The Avengers" },
    { title: "Forrest Gump" },
    { title: "The Silence of the Lambs" },
    { title: "Jurassic Park" },
    { title: "Raiders of the Lost Ark" },
    { title: "Indiana Jones and the Last Crusade" },
    { title: "Jurassic Park" },
    { title: "The Terminator" },
    { title: "Terminator 2: Judgment Day" },
    { title: "Alien" },
    { title: "Aliens" },
    { title: "The Shawshank Redemption" },
    { title: "The Green Mile" },
    { title: "Se7en" },
    { title: "The Usual Suspects" },
    { title: "The Departed" },
    { title: "Casino" },
    { title: "Heat" },
    { title: "The Big Lebowski" },
    { title: "No Country for Old Men" },
    { title: "Fargo" },
    { title: "Blade Runner" },
    { title: "Blade Runner 2049" },
    { title: "Mad Max: Fury Road" },
    { title: "The Matrix Reloaded" },
    { title: "The Matrix Revolutions" },
    { title: "Fight Club" },
    { title: "American History X" },
    { title: "American Psycho" },
    { title: "A Clockwork Orange" },
    { title: "The Shining" },
    { title: "Full Metal Jacket" },
    { title: "Apocalypse Now" },
    { title: "Saving Private Ryan" },
    { title: "Platoon" },
    { title: "Dunkirk" },
    { title: "The Bridge on the River Kwai" },
    { title: "Lawrence of Arabia" },
    { title: "12 Years a Slave" },
    { title: "Schindler's List" },
    { title: "The Pianist" },
    { title: "The Sound of Music" },
    { title: "Singin' in the Rain" },
    { title: "The Wizard of Oz" },
    { title: "Casablanca" },
    { title: "Gone with the Wind" },
    { title: "Citizen Kane" },
    { title: "It's a Wonderful Life" },
    { title: "Rear Window" },
    { title: "Vertigo" },
    { title: "North by Northwest" },
    { title: "Psycho" },
    { title: "Taxi Driver" },
    { title: "Raging Bull" },
    { title: "The Godfather Part II" },
    { title: "Apocalypse Now" },
    { title: "One Flew Over the Cuckoo's Nest" },
    { title: "Chinatown" },
    { title: "Good Will Hunting" },
    { title: "Dead Poets Society" },
    { title: "The Breakfast Club" },
    { title: "Ferris Bueller's Day Off" },
    { title: "Stand by Me" },
    { title: "The Goonies" },
    { title: "E.T. the Extra-Terrestrial" },
    { title: "Back to the Future" },
    { title: "Ghostbusters" },
    { title: "The Karate Kid" },
    { title: "The Princess Bride" },
    { title: "Groundhog Day" },
    { title: "The Truman Show" },
    { title: "Eternal Sunshine of the Spotless Mind" },
    { title: "Lost in Translation" },
    { title: "The Grand Budapest Hotel" },
    { title: "Her" },
    { title: "Birdman" },
    { title: "Whiplash" },
    { title: "La La Land" },
    { title: "Moonlight" },
    { title: "The Shape of Water" },
    { title: "Get Out" },
    { title: "Black Panther" },
    { title: "The Social Network" },
    { title: "The King's Speech" },
    { title: "Slumdog Millionaire" },
    { title: "Million Dollar Baby" },
    { title: "The Hurt Locker" },
    { title: "12 Years a Slave" },
    { title: "Birdman or (The Unexpected Virtue of Ignorance)" },
    { title: "The Artist" }
];

export default movies;
